<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_newestOrderID</name>
   <tag></tag>
   <elementGuidId>924a7874-5c11-4d4d-9478-a3f1200d7044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Content']/table/tbody/tr[last()]/td[1]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(13) > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;83553&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dbf447e9-9073-4f65-971d-c235a60b4c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>83553</value>
      <webElementGuid>4def65c8-e565-4b83-be58-0484a2c68842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/table[1]/tbody[1]/tr[13]/td[1]</value>
      <webElementGuid>7991cf26-013c-479c-aada-eaae142a595d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/table/tbody/tr[13]/td</value>
      <webElementGuid>bc07528b-7983-4366-bf71-1d99056fa168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$18.50'])[1]/following::td[1]</value>
      <webElementGuid>d2a4c292-cdb8-48a7-aba1-a5463f0aaa9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$35.00'])[1]/following::td[4]</value>
      <webElementGuid>39dc3165-4fd7-4eba-837c-f902479cfd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$193.50'])[10]/preceding::td[2]</value>
      <webElementGuid>0beea24d-2719-4b87-aafc-57350952d92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td</value>
      <webElementGuid>706a5042-62b9-4183-a3bf-59a357c5f87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '83553' or . = '83553')]</value>
      <webElementGuid>01bb00db-6364-4f9b-92fd-7adaf0ce9ba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
